### ISSUE TITLE
Issue with logback less than 1.1.8

### ISSUE THREAD

**Issue by fadjer** [osiegmar/logback-gelf#10]
Hi,

In your doc you say that this lib work with logback 1.1.3 or later.  It does not work with logback 1.1.7. I was facing this issue before upgrading to 1.1.8 : 

https://github.com/logstash/logstash-logback-encoder/issues/160

Thx

**Comment by osiegmar** [comment]
This lib is compatible with logback 1.1.3 or later. But logback 1.1.7 had a bug: https://jira.qos.ch/browse/LOGBACK-1158

Duplicate of #1

**Comment by fadjer** [comment]
Many thanks for documentation improvement...
