### ISSUE TITLE
It reports only Sl4j logs not console logs

### ISSUE THREAD

**Issue by senolatac** [osiegmar/logback-gelf#107]
**Describe the bug**
doesn't send all console logs.

**To Reproduce**
https://github.com/senolatac/hexagonal-architecture-demo/blob/dev/application/src/main/resources/logback-spring.xml

**Additional context**
* Java distribution and version in use (output of `java -version`): java 17
* SLF4J and Logback version in use
* Graylog version in use
* https://github.com/senolatac/hexagonal-architecture-demo/blob/dev/pom.xml
* More detail: https://stackoverflow.com/questions/78592920/send-all-exceptions-console-sl4j-logs-to-graylog

**Comment by osiegmar** [comment]
As a log appender for Logback, this library forwards anything to Graylog as long as Logback is configured accordingly. Please check your logback configuration. You may want to start with simpler configuration as shown in this projects [README](https://github.com/osiegmar/logback-gelf/blob/master/README.md). It seems that you currently route specific logs to console only.

**Comment by senolatac** [comment]
@osiegmar thanks for your reply but it looks like a problem on others as well: https://community.graylog.org/t/unable-to-see-stracktrace-in-graylog/24817

**Comment by osiegmar** [comment]
From what I can see in that post from 2022, that guy had two different log libraries in place!

The line starting with `2022-07-17 14:06:49,307` is from logback and that line was also sent to Graylog.
The line `Jul 17, 2022 2:06:49 PM` was most likely produced by `java.util.logging` or some other log library but not from Logback!

For consistent logging you need to make sure that all Logs are sent via Logback. Besides Logback and SLF4J, no other log library must exist on classpath. If other dependencies require commons-logging, java.util.logging or some other log libraries, you need to bridge them – see https://www.slf4j.org/legacy.html.
