### ISSUE TITLE
GraylogHost can support multiple addresses?

### ISSUE THREAD

**Issue by mrdear** [osiegmar/logback-gelf#11]
Graylog master-slave mode, when a service a large number of anomalies for a short time, then crazy hit a node, here want to do load balancing, then you can configure multiple addresses on the client?

**Comment by osiegmar** [comment]
No. Currently this library doesn't support client side load balancing.

**Comment by osiegmar** [comment]
I have introduced a simple connection pool in branch connection-pool. This does not allow to configure several addresses but if a dns record points to several addresses, round robin would be used. Just take a look...

**Comment by mrdear** [comment]
I'm not sure if udp mode uses connection pool to send to different graylog server for missing log.

My current solution uses the logback variable, which configures multiple connections in the application and randomly selects a binding when the project starts up.

**Comment by osiegmar** [comment]
The udp mode doesn't need to use connection pooling, but it uses the AddressResolver now as well to ensure client side load balancing.

**Comment by osiegmar** [comment]
fixed in 1.1.0 which has just been released
