### ISSUE TITLE
Use property as a variable in staticField

### ISSUE THREAD

**Issue by Snake-Tn** [osiegmar/logback-gelf#17]
I'm new to JAVA stack and I may seem totally lost.

I want logback to send the environment name to graylog as field. so I can create a stream based on that field (prod,stage,dev..)

To achieve this, I created a file under resources called _application.properties_ containing:
`environment=dev`

into _backlog.xml_ I added : `<staticField>environment:${environment}</staticField>`
After that, in gray log I'm receiving : **environment environment_IS_UNDEFINED**

Do you know how can I achieve this? any reference to documentation is welcome.
Thanks for your help!

**Comment by osiegmar** [comment]
Usually environment variables have to come from the environment (export on Linux/Unix and set on Windows). Settings variables in a `application.properties` file sounds like your using Spring Boot. Using those settings within a logback configuration is not supported by logback directly. But with Spring Boot you can -- see [26.6.2 Environment Properties](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#_environment_properties) of the spring documentation.
