### ISSUE TITLE
Remote Graylog

### ISSUE THREAD

**Issue by willherrera** [osiegmar/logback-gelf#18]
Hey there,
How are you?

I have 2 graylog servers(1 locally and another published), I can send logs in the graylog locally but when I change grayloghost to the other graylog, it doesn't receive. Do you have any ideia how to send data from differents java application in differents networks to one graylog centralized?

**Comment by osiegmar** [comment]
It doesn't matter if the graylog server runs on the local machine or on a remote one. The question is just, is the right port and protocol configured in that graylog instance, does the hostname (if no ip is used) resolve to the right ip, does the network/gatway route correctly and does outgoing or ingoing firewall rules permit the traffic.

At the end of the page at http://docs.graylog.org/en/2.4/pages/gelf.html you find some command line examples of how to test graylog/gelf communication directly. Use can use this to troubleshoot. If you're using UDP, it'd switch to TCP (don't forget to configure this as an input in graylog!) for testing/troubleshooting purposes, as UDP makes testing harder as it is fire and forget...
