### ISSUE TITLE
GELF message time - UTC, how change?

### ISSUE THREAD

**Issue by kixiro** [osiegmar/logback-gelf#19]
I did not find the possibility of changing the GELF message time (send - UTC, i'm work in utc+3). Is this possible in the current release?

**Comment by osiegmar** [comment]
GELF defines the timestamp to be passed as an unix timestamp (seconds till 1/1/1970 in UTC). See [Graylog documentation](http://docs.graylog.org/en/2.4/pages/users_and_roles/users.html) for handling timezones (user specific) within Graylog.
