### ISSUE TITLE
Formatting issue when logging exception object

### ISSUE THREAD

**Issue by mfriess2** [osiegmar/logback-gelf#22]
When we log something like this: 
```
try {
    throw new RuntimeException("Some exception message")
} catch(RuntimeException runtimeException) {
    slf4JLogger.error("Some message: {}", 123, runtimeException)
}
```

then we see in Kibana as message: 
```
August 28th 2018, 19:23:50.184    ERROR     Some message: 123java.lang.RuntimeException: Some exception message
    at [...]
    at [...]
```
-> as you can see, the exception is suffixed without newline to the log message!

In our Log4j appegged like this:
```
2018-08-28 19:23:50.184   ERROR   [...]   Some message: 123

java.lang.RuntimeException: Some exception message
    at [...]
    at [...]
```

Is this a bug? Where does the difference come from?
We understand that slf4j auto-appends the exception to the message if e.g. "%noexp" is not explicitly specified. But in log4j the formatting comes out readable whereas with logback-gelf we have this problem.

Any help is highly appreciated!

**Comment by osiegmar** [comment]
The output in Kibana depends on the configured log pattern layout (default "%m"). You can easily change it (for example to "%m%n") within the appender configuration:

```xml
<layout class="de.siegmar.logbackgelf.GelfLayout">
    <fullPatternLayout class="ch.qos.logback.classic.PatternLayout">
        <pattern>%m%n</pattern>
    </fullPatternLayout>
</layout>
```

See https://logback.qos.ch/manual/layouts.html#ClassicPatternLayout for a full reference of slf4j log pattern configuration.

Please let me know, if changing the pattern to "%m%n" solved your problem.
