### ISSUE TITLE
All statics fields are prefixed by _ if we log in the run method of thread

### ISSUE THREAD

**Issue by ibouakl** [osiegmar/logback-gelf#25]
Hello @osiegmar ,

We noticed if we log in the run method of a thread, all statics fields are prefixed by _ 

Example :  when we call a method  from the run method of thread,  statics fields are prefixed by _ ( _app_name instead of app_name for example)

if we call the same method from http endpoint, all static fields are ok (not prefixed with underscore) 

Did we miss a configuration ? Any suggestions please ?

Thank you for your help.

**Comment by osiegmar** [comment]
As written in the [GELF specification](http://docs.graylog.org/en/3.0/pages/gelf.html):
> every field you send and prefix with an underscore (_) will be treated as an additional field. 

This is why this library automatically prefixes any additional field with an underscore character. Otherwise the payload would contain invalid field names.
