### ISSUE TITLE
how to dynamic add staticField

### ISSUE THREAD

**Issue by lly835** [osiegmar/logback-gelf#26]
i want to dynamic  set springboot application name.
```
<staticField>app_name:${spring.application.name}</staticField>
```

**Comment by osiegmar** [comment]
This is provided by the [springProperty tag for logback](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_environment_properties) of Spring Boot. Make sure that the logback configuration file has the name `logback-spring.xml` to support this.
