### ISSUE TITLE
"no applicable action"

### ISSUE THREAD

**Issue by forsberg** [osiegmar/logback-gelf#28]
Trying out logback-gelf 2.0.0, GELF logging did not happen, and enabling logging.debug in logback made this show up:

    12:45:38,253 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/etc/logger-conf/..data/logback-graylog.xml] at [file:/etc/logger-conf/..data/logback-graylog.xml]
    12:45:38,572 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
    12:45:38,576 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
    12:45:38,597 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
    12:45:38,697 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [de.siegmar.logbackgelf.GelfTcpAppender]
    12:45:38,699 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [GELF]
    12:45:38,719 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@23:59 - no applicable action for [layout], current ElementPath  is [[configuration][appender][layout]]
    12:45:38,719 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@24:32 - no applicable action for [includeRawMessage], current ElementPath  is [[configuration][appender][layout][includeRawMessage]]
    12:45:38,726 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@25:28 - no applicable action for [includeMarker], current ElementPath  is [[configuration][appender][layout][includeMarker]]
    12:45:38,726 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@26:29 - no applicable action for [includeMdcData], current ElementPath  is [[configuration][appender][layout][includeMdcData]]
    12:45:38,726 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@27:32 - no applicable action for [includeCallerData], current ElementPath  is [[configuration][appender][layout][includeCallerData]]
    12:45:38,727 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@28:35 - no applicable action for [includeRootCauseData], current ElementPath  is [[configuration][appender][layout][includeRootCauseData]]
    12:45:38,727 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@29:31 - no applicable action for [includeLevelName], current ElementPath  is [[configuration][appender][layout][includeLevelName]]
    12:45:38,727 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@30:78 - no applicable action for [shortPatternLayout], current ElementPath  is [[configuration][appender][layout][shortPatternLayout]]
    12:45:38,727 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@31:26 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][layout][shortPatternLayout][pattern]]
    12:45:38,728 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@33:77 - no applicable action for [fullPatternLayout], current ElementPath  is [[configuration][appender][layout][fullPatternLayout]]
    12:45:38,728 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@34:26 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][layout][fullPatternLayout][pattern]]
    12:45:38,729 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@36:26 - no applicable action for [staticField], current ElementPath  is [[configuration][appender][layout][staticField]]
    12:45:38,729 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@37:26 - no applicable action for [staticField], current ElementPath  is [[configuration][appender][layout][staticField]]
    12:45:38,772 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
    12:45:38,774 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC GELF]
    12:45:38,774 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [GELF] to ch.qos.logback.classic.AsyncAppender[ASYNC GELF]
    12:45:38,774 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC GELF] - Attaching appender named [GELF] to AsyncAppender.
    12:45:38,781 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC GELF] - Setting discardingThreshold to 51
    12:45:38,786 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
    12:45:38,787 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC STDOUT]
    12:45:38,787 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to ch.qos.logback.classic.AsyncAppender[ASYNC STDOUT]
    12:45:38,787 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC STDOUT] - Attaching appender named [STDOUT] to AsyncAppender.
    12:45:38,787 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC STDOUT] - Setting discardingThreshold to 51
    12:45:38,787 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
    12:45:38,787 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC STDOUT] to Logger[ROOT]
    12:45:38,788 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC GELF] to Logger[ROOT]
    12:45:38,788 |-ERROR in ch.qos.logback.core.joran.action.ShutdownHookAction - Missing class name for shutdown hook. Near [shutdownHook] line 55
    12:45:38,788 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.

logback-classic version used is 1.2.3.

My configuration:

```xml
<configuration scan="true">
<!-- Changes to this configuration will be applied automatically within one minute,
     i.e, you can reload the configmap and the changes will be applied within approximately
     a minute -->

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="GELF" class="de.siegmar.logbackgelf.GelfTcpAppender">
        <graylogHost>graylog-node.monitoring.svc.cluster.local</graylogHost>
        <graylogPort>12300</graylogPort>
        <connectTimeout>15000</connectTimeout>
        <reconnectInterval>300</reconnectInterval>
        <maxRetries>2</maxRetries>
        <retryDelay>3000</retryDelay>
        <poolSize>2</poolSize>
        <poolMaxWaitTime>5000</poolMaxWaitTime>
        <layout class="de.siegmar.logbackgelf.GelfLayout">
            <includeRawMessage>false</includeRawMessage>
            <includeMarker>true</includeMarker>
            <includeMdcData>true</includeMdcData>
            <includeCallerData>true</includeCallerData>
            <includeRootCauseData>true</includeRootCauseData>
            <includeLevelName>true</includeLevelName>
            <shortPatternLayout class="ch.qos.logback.classic.PatternLayout">
                <pattern>%m%nopex</pattern>
            </shortPatternLayout>
            <fullPatternLayout class="ch.qos.logback.classic.PatternLayout">
                <pattern>%m</pattern>
            </fullPatternLayout>
            <staticField>ncs-service:grpc</staticField>
            <staticField>namespace:erfor</staticField>
        </layout>
    </appender>

    <appender name="ASYNC GELF" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="GELF" />
    </appender>

    <appender name="ASYNC STDOUT" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="STDOUT" />
    </appender>


    <root level="info">
        <appender-ref ref="ASYNC STDOUT" />
        <appender-ref ref="ASYNC GELF" />
    </root>

    <shutdownHook/>

</configuration>
```
Reverting to logback-gelf 1.1.0 resolves the problem. 

Seems a bit similar to #6

**Comment by osiegmar** [comment]
The configuration format of logback-gelf 2.0 has changed a bit, to reflect the logback api changes.

Instead of

`<layout class="de.siegmar.logbackgelf.GelfLayout">`

you have to use

`<encoder class="de.siegmar.logbackgelf.GelfEncoder">`

This is not related to #6.

**Comment by forsberg** [comment]
Aha, that explains it. May I suggest that you mention this incompatibility in the [release notes for 2.0.0](https://github.com/osiegmar/logback-gelf/releases/tag/v2.0.0)?

**Comment by forsberg** [comment]
Oh, and btw, many thanks for your quick reply! :-)

**Comment by osiegmar** [comment]
You're right. I've added it to the README.md (important notes). Thanks!
