### ISSUE TITLE
Raise Manifest version to 2

### ISSUE THREAD

**Issue by maweck** [osiegmar/logback-gelf#31]
In some contexts the library can't be used as the following error message is thrown:

> Unsupported 'Bundle-ManifestVersion' value: 1

The error message comes from Karaf which does not seem to support the old Manifest version. - Is there a way to raise the version?

Thank you and best regards!

**Comment by osiegmar** [comment]
This library has no (explicit) support for OSGi and does *not* have this header configured in its `META-INF/MANIFEST.MF` file at all. After searching for that error message, I could find this bug ticket: https://issues.apache.org/jira/browse/KARAF-4692 -- which is a (fixed) bug in Apache Karaf.

**Comment by maweck** [comment]
Thank you for the effort and the fast reply! 

So we will ask the vendor to raise the Karaf version - As this might take a while I'll close the issue for now. Thank you once again :)
