### ISSUE TITLE
Reconnect load balancer

### ISSUE THREAD

**Issue by jbye** [osiegmar/logback-gelf#33]
Hi,

With long lasting tcp connections to our Graylog load balancer we have trouble balancing the load across our cluster if a node is restarted.

Could you elaborate whether the reconnect functionality would help this situation? My understanding after reading the docs is that it would force a reconnect to the load balancer every N seconds, and thus should help this issue.

Thank you :)

**Comment by osiegmar** [comment]
It is difficult to tell without knowing your configuration and setup. The default `reconnectInterval` would ensure, that no connection is used longer than 60 seconds - after that time a new connection would be opened to the configured `graylogHost`. If the `graylogHost` name resolves to multiple ip addresses, round robin will be used. This combination should perfectly match your requirements.
