### ISSUE TITLE
StaticField add fail 

### ISSUE THREAD

**Issue by teemo2009** [osiegmar/logback-gelf#37]
add a staticField  in logback.xml   "<staticField>order_id:{orderId}</staticField>".

My interface

  /**
     * vin logger
     *
     * @param orderId          
     * @param content       
     * @date 2019/9/12_14:06
     */
    @PutMapping("/vin")
    public void vin(@RequestParam("orderId") String orderId,
                    @RequestParam("content") String content) {
        MDC.put("orderId", orderId);
        log.info(content);
    }

when orderId  was  number,It was ok,garylog console sout this message
but  orderId like "2e22a1e1a68a4dde94c73ea56e04d914",no error,garylog was't  this message.
I need your help!

**Comment by osiegmar** [comment]
You are mixing up two different things – if you want to pass additional log information with MDC you have to ensure that the configuration option `includeMdcData` is enabled. This has nothing to do with static fields, which would not be useful in your example.

**Comment by teemo2009** [comment]
> You are mixing up two different things – if you want to pass additional log information with MDC you have to ensure that the configuration option `includeMdcData` is enabled. This has nothing to do with static fields, which would not be useful in your example.

lol！ok！
