### ISSUE TITLE
milliseconds accuracy

### ISSUE THREAD

**Issue by jeusdi** [osiegmar/logback-gelf#47]
I'm get messages on screen rounded to seconds:

![image](https://user-images.githubusercontent.com/941639/76312088-958e3300-62d2-11ea-8c8b-a7cc106a8de0.png)

So, it drive me to misread log messages.

I'm sending them using this maven package (logback-gelf):

    <dependency>
        <groupId>de.siegmar</groupId>
        <artifactId>logback-gelf</artifactId>
        <version>2.2.0</version>
    </dependency>

logback configuration is:

    <configuration>
        <include resource="org/springframework/boot/logging/logback/base.xml" />
        <include resource="org/springframework/boot/logging/logback/console-appender.xml" />

        
        <logger name="net.gencat.transversal.espaidoc.common.dao.RedisDao" level="WARN" additivity="false" />

        <springProperty scope="context" name="ACTIVE_PROFILE" source="spring.profiles.active"/>

        <appender name="GELF" class="de.siegmar.logbackgelf.GelfTcpAppender">
            <graylogHost>localhost</graylogHost>
            <graylogPort>12201</graylogPort>
            <connectTimeout>15000</connectTimeout>
            <reconnectInterval>300</reconnectInterval>
            <maxRetries>2</maxRetries>
            <retryDelay>3000</retryDelay>
            <poolSize>2</poolSize>
            <poolMaxWaitTime>5000</poolMaxWaitTime>
            <encoder class="de.siegmar.logbackgelf.GelfEncoder">
                <originHost>localhost</originHost>
                <includeRawMessage>true</includeRawMessage>
                <includeMarker>true</includeMarker>
                <includeMdcData>true</includeMdcData>
                <includeCallerData>true</includeCallerData>
                <includeRootCauseData>false</includeRootCauseData>
                <includeLevelName>true</includeLevelName>
                <shortPatternLayout class="ch.qos.logback.classic.PatternLayout">
                    <pattern>%m%nopex</pattern>
                </shortPatternLayout>
                <fullPatternLayout class="ch.qos.logback.classic.PatternLayout">
                    <pattern>%m%n</pattern>
                </fullPatternLayout>
                <numbersAsString>false</numbersAsString>
                <staticField>service_name:api-${ACTIVE_PROFILE}</staticField>
            </encoder>
        </appender>

        
        <appender name="ASYNC GELF" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="GELF" />
        </appender>

        <logger name="net.gencat.transversal.espaidoc" level="debug" additivity="false">
            <appender-ref ref="ASYNC GELF" />
            <appender-ref ref="CONSOLE" />
        </logger>

        <logger name="net.gencat.transversal.espaidoc.api.service.RepositoryService" level="debug" additivity="false">
            <appender-ref ref="CONSOLE" />
        </logger>

        <logger name="net.gencat.transversal.espaidoc.api.dao.RepositoryDocumentDao)" level="debug" additivity="false">
            <appender-ref ref="CONSOLE" />
        </logger>
    </configuration>

Any ideas?

**Comment by osiegmar** [comment]
This library uses timestamps with millisecond precision.

I suspect a misconfiguration in your Graylog installation. As I don't see it in your screenshot – which field are you displaying? Is it the 'timestamp' field? Have you configured a pipeline rule which might cause this effect?

Could you try `curl` to debug this a bit further? You can find examples in the [Graylog documentation about GELF](https://docs.graylog.org/en/3.2/pages/gelf.html).

**Comment by jeusdi** [comment]
A posted the same question on graylog forums at [this post](https://community.graylog.org/t/milliseconds-acuracy/14424).

1. Yes, the field displayed is `timestamp`.
2. The only pipeline rule I have is:
```
rule "uploaded size"
when
  starts_with(to_string($message.message), "Verificant si hi ha", true)
then
  let extract = grok("%{BASE10NUM:uploaded_size;long}", replace(to_string($message.message), "."), false);
  set_fields(extract);
end
```
3. I've tested with: `echo -n -e '{ "version": "1.1", "host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }'"\0" | nc -w0 localhost 12201`
The problem remains:
![image](https://user-images.githubusercontent.com/941639/76502719-d73eeb00-6444-11ea-83bb-436054f0b89a.png)


They are telling that theproblem is from elasticsearch...
Do you really think is that?

Do you see t

**Comment by osiegmar** [comment]
I don’t think, this issue is related to elasticsearch and ES is definitely capable of storing timestamps with millisecond precision (see [Date datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html)).

As you can see in your own (latest) screenshot, the milliseconds are recorded. There are three timestamps displayed in the screenshot – two are missing the milliseconds and one is showing them. If you click on the UUID you will probably see even more fields with millisecond precision.

I tried to reproduce the problem and was able to reproduce it with Graylog 3.2.3. In Graylog 3.1.4 milliseconds are shown everywhere.

I hope I could help a little with this, but I close this ticket now as this is not a logback-gelf issue at all.
