### ISSUE TITLE
[question] Performance of GelfUdpAppender

### ISSUE THREAD

**Issue by eshepelyuk** [osiegmar/logback-gelf#5]
Hello @osiegmar, 

I'd like to ask about following line

https://github.com/osiegmar/logback-gelf/blob/master/src/main/java/de/siegmar/logbackgelf/GelfUdpAppender.java#L73

According to `InetSocketAddress` javadoc

>> An attempt will be made to resolve the hostname into an InetAddress. If that attempt fails, the address will be flagged as unresolved.

So, I assume this line is affecting logging performance since host / port resolution happens on each log statement.

What do you think ?

**Comment by osiegmar** [comment]
Hi @eshepelyuk,

thanks for pointing out the unresolved flag. I should check that and skip the send operation if I do not have a resolved address.

About the performance of address resolution: I think it's the job of the underlying JVM (see java.net.InetAddress#getCachedAddresses), operating system or additional DNS resolvers / caches to keep that fast. Especially in cloud environments it's not uncommon that IP addresses of graylog servers may change regularly. A reasonable DNS cache would cache an address based on the DNS record TTL (or zone NTTL).

I did a quick performance test (via InetSocketAddress). It took 0.20 sec to resolve a hostname 1,000,000 times.

Bye

Oliver

**Comment by osiegmar** [comment]
Now, I had time to investigate the unresolved flag handling. Checking the unresolved flag is not required. An UnresolvedAddressException is thrown when trying to send data through the channel.
