### ISSUE TITLE
Support basic auth

### ISSUE THREAD

**Issue by robstoll** [osiegmar/logback-gelf#50]
Would be nice if you support basic auth in addition

**Comment by osiegmar** [comment]
This library is talking to Graylogs UDP or TCP GELF input. I don't see how OAuth could be used there. Please provide more details.

**Comment by robstoll** [comment]
For instance, imagine you have a ngnix in front which requires basic auth

**Comment by osiegmar** [comment]
I'm a bit confused. Now you're talking about "basic auth" but were mentioning "oAuth" in the title and first post.
Anyway, a reverse proxy in front of Graylog (used for authentication) sounds like you want to pass logs via HTTP(s). This protocol is not supported by this library and I don't have any plan to add it.

**Comment by robstoll** [comment]
sorry, I meant basic auth

**Comment by robstoll** [comment]
closing it then again
