### ISSUE TITLE
Usage as code

### ISSUE THREAD

**Issue by louis030195** [osiegmar/logback-gelf#54]
Is there any example to setup this as code (i.e. tweak the loggers / appenders ...) in Java / Kotlin ? I intend to use it for several projects, it's more practical and maintainable than doing some XML tweaks.

Thanks !

**Comment by osiegmar** [comment]
The logback configuration is simply setter based. You could check out the tests at https://github.com/osiegmar/logback-gelf/tree/master/src/test/java/de/siegmar/logbackgelf to see programmatic use of the API.

**Comment by louis030195** [comment]
Awesome thanks !
