### ISSUE TITLE
Add the possibility to filter included MDC keys

### ISSUE THREAD

**Issue by fabiojb** [osiegmar/logback-gelf#60]
Using logback-gelf with spring-cloud-sleuth works just fine, and I can index sleuth fields like "traceId" and "spanId" on every log. But for some reason sleuth duplicates the values on two different MDC entries, traceId -> X-B3-TraceId and spanId -> X-B3-SpanId (and other undesired MDC entries).

Having the possibility to filter the MDC data that is included will be interesting for this and other cases I think.

**Comment by osiegmar** [comment]
Those legacy MDC fields were removed in sleuth 3.0.0. See https://github.com/spring-cloud/spring-cloud-sleuth/issues/1221.

**Comment by osiegmar** [comment]
Version 4 introduced [MdcDataFieldMapper](https://github.com/osiegmar/logback-gelf/blob/master/src/main/java/de/siegmar/logbackgelf/mappers/MdcDataFieldMapper.java) that can be used to programmatically add any kind of filtering logic.

**Comment by osiegmar** [comment]
I'm closing this issue because filtering can be easily added by custom field mappers (implemented like the mentioned MdcDataFieldMapper) and I do not want to further increase the complexity if not required.
