### ISSUE TITLE
GZIP Compression with GelfUdpAppender

### ISSUE THREAD

**Issue by Stratehm** [osiegmar/logback-gelf#66]
**Problem:**
We have an application that sends logs to a Logstash instance but all special characters are badly handled. It seems that Logstash has a problem when using ZLIB compression but works well with GZIP compression (tested and approved). (https://github.com/logstash-plugins/logstash-input-gelf/issues/54)

**Solution**
We would like to be able to use GZIP compression instead of ZLIB since this compression method is also permitted in the GELF specs: https://docs.graylog.org/docs/gelf#gelf

A solution may be to add a `<compressionMethod>GZIP/ZLIB</compressionMethod>` configuration to the GelfUdpAppender and taken into account only if `<useCompression>` is `true`.

**Alternative solution**
Remove `<useCompression>` configuration (breaking change) and replace it with `<compressionMethod>None/GZIP/ZLIB</compressionMethod>`

**Comment by osiegmar** [comment]
Thanks for your contribution. The functionality will be part of the next non-patch release.
