### ISSUE TITLE
Update logback-classic to 1.2.8

### ISSUE THREAD

**Issue by shurkanTwo** [osiegmar/logback-gelf#67]
**Describe the bug**
There might be a similar security issue in logback-classic as in Log4J.
Therefore we would like to have a new version of logback-gelf with the updated version of logback-classic.

Also see:
https://logback.qos.ch/news.html
https://jira.qos.ch/browse/LOGBACK-1591

**Comment by shurkanTwo** [comment]
@osiegmar Will you also create a release?

**Comment by osiegmar** [comment]
Yes, it's on the way. Nexus is simply pretty busy right now – don't know why ;-)

**Comment by shurkanTwo** [comment]
@osiegmar  yes it is a bit chaotic atm, thanks a lot!
