### ISSUE TITLE
tcp configuration error

### ISSUE THREAD

**Issue by oushitian** [osiegmar/logback-gelf#75]
java 8
logback

![image](https://user-images.githubusercontent.com/34906984/147450905-06b8c2d6-f813-4802-bd53-7c81ac0cf0af.png)
this is my tcp configuration,
![image](https://user-images.githubusercontent.com/34906984/147450948-037bccd3-86a1-41c4-8434-33b4dff2aa79.png)
this is a log error, how can i solve it?

**Comment by osiegmar** [comment]
From what I see, I suspect a configuration mismatch.

* What does your Graylog input configuration looks like? Did you configure a TCP input on that port or is it a UDP input?
* Does logging via netcat work (see https://docs.graylog.org/docs/gelf#example-payload)?

If you suspect a bug in logback-gelf please provide a test case.

**Comment by oushitian** [comment]
i have configure a TCP input in Graylog,  if i configure like it:
![image](https://user-images.githubusercontent.com/34906984/147467644-f9f16500-2bcd-4a4d-8048-5413e3696499.png)
It can run on Linux and MacOS without any problem.then if i configure like it:
![image](https://user-images.githubusercontent.com/34906984/147467708-25186036-5754-44ba-bb36-c736624cfaa8.png)
it can not run in Linux， but can run in my local MacOS no problem，I think the problem may be "GelfEncoder Class"?

**Comment by osiegmar** [comment]
I'm afraid those screenshots doesn't really help.

* The configuration doesn't show the Graylog / server side
* The two questions from my last post remain unanswered
* Screenshots should avoided if possible as their content is not indexed for search

This library is working flawlessly on a number of Linux machines. As I said:

> If you suspect a bug in logback-gelf please provide a test case.
