### ISSUE TITLE
Mutual TLS fails, 

### ISSUE THREAD

**Issue by tparkercbn** [osiegmar/logback-gelf#79]
**Describe the bug**
Logback TLS doesn't seem to support mutual-TLS when talking to a GELF server that requires a client certificate to be presented.

No test cases.  But log4j in the same Tomcat server (different app, same keystore file) connects properly using mutual TLS and logback does not.

logback:
```
*** ServerHelloDone
Warning: no suitable certificate found - continuing without client authentication
*** Certificate chain
<Empty>
***
```

log4j:
```
*** ServerHelloDone
matching alias: development_dev-test_a8devintweb-dev
*** Certificate chain
chain [0] = <redacted contents of my certificate>
```

**Additional context**
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

SLF4J and Logback version in use.
logback-core-1.2.3.jar
logback-classic-1.2.3.jar
logback-gelf-4.0.0.jar
slf4j-api-1.7.25.jar

**Comment by osiegmar** [comment]
Duplicates #27
