### ISSUE TITLE
GelfMessage should fail on host = "", shortmessage=""

### ISSUE THREAD

**Issue by ipavkovic** [osiegmar/logback-gelf#82]
**Describe the bug**
We have a logging with a short message "" (coming from the root cause NullPointerException)

GelfMessage checks for null but not empty message. Our Graylog server silently skips a message with short_message = ""  even if full message is filled properly

```
        this.host = Objects.requireNonNull(host, "host must not be null");
        this.shortMessage = Objects.requireNonNull(shortMessage, "shortMessage must not be null");
```
should be changed to something like

```
        this.host = requireNotEmpty(host, "host must not be empty");
        this.shortMessage = requireNotEmpty(shortMessage, "shortMessage must not be empty");
[...]
       private static void requireNotEmpty(String value, String message) {
         if (value == null || value.trim().isEmpty()) {
           throw new IllegalStateException(message);
         }
       }
```

insert test code here
```

**Comment by osiegmar** [comment]
Which version of graylog-server do you use?

**Comment by osiegmar** [comment]
According to [GelfCodec.java](https://github.com/Graylog2/graylog2-server/blob/8051aae60d436beef614f0acbbf1b8306a530508/graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java#L262), Graylog requires a `short_message` that "is not blank" (by using Apache Commons Lang3 StringUtils). The definition of blank by `org.apache.commons.lang3.StringUtils#isBlank`:

> Checks if a CharSequence is empty (""), null or whitespace only. Whitespace is defined by [Character.isWhitespace(char)](java.lang.Character#isWhitespace(char)).

So this will be changed in the next release of this library.
