### ISSUE TITLE
Add ability to log formatted time

### ISSUE THREAD

**Issue by dstrelec** [osiegmar/logback-gelf#85]
**Is your feature request related to a problem? Please describe.**
Centralized logging platform in used place is configured to use string `formatted_time` field in addition to `timestamp` field.

**Describe the solution you'd like**
Additional GELF encoder configuration where we would be able to setup additional properties for logging formatted time string field like:
```
<includeFormattedTime>true</includeFormattedTime>
<formattedTimeKey>time_name</formattedTimeKey>
<formattedTimePattern>yyyy-MM-dd'T'HH:mm:ss.SSSXXX</formattedTimePattern>
```

**Comment by osiegmar** [comment]
Please implement a custom field mapper for that. See https://github.com/osiegmar/logback-gelf/discussions/87.
