### ISSUE TITLE
Several minor improvements

### ISSUE THREAD

**Issue by magicprinc** [osiegmar/logback-gelf#90]
List of changes (PR follows)

1) much better HostName detection
If docker is installed, then a usual method (like in your util class) returns host.docker.internal

2) one can override HostName with system property: logstash-gelf.hostname

3) platform dependent line endings to network standard ("\n")
Your original tests fail on Windows machine.

4) gradle-7.6.2-all
Simply nice to have and debug

5) api 'ch.qos.logback:logback-classic:1.2.12' and verion up to 4.0.3

**Comment by osiegmar** [comment]
Please don't mix multiple changes in one issue/PR. Will react on the PR later.
