### ISSUE TITLE
Faster MessageIdSupplier with less object allocation, error-prone

### ISSUE THREAD

**Issue by magicprinc** [osiegmar/logback-gelf#93]
1) MessageIdSupplier Supplier<Long> → LongSupplier: less object allocation (temporary Longs)

2) System.nanoTime is quite slow → AtomicLong with random starting value

3) error-prone (google static code analyzer / linter)

4) error-prone has found some minor problems: fixed 

https://github.com/magicprinc/logback-gelf/commits/feature/messageIdSupplier

I would send it as PR later

**Comment by osiegmar** [comment]
Thanks for the hint on LongSuppliert – implemented it by f426aebcb1178012516f1bb8a49b44ad416baa2b. Will react on the PR later.
